name: coding-standards

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pint:
    runs-on: ubuntu-latest
    name: Pint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Check code style
        run: vendor/bin/pint --test

  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse --no-progress
